bindAddr = "0.0.0.0"
bindPort = 443

transport.tls.force = true
transport.tls.certFile = "/data/certs/cert.crt"
transport.tls.keyFile = "/data/certs/key.key"
transport.tls.trustedCaFile = "/data/certs/ca.crt"

auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

allowPorts = [
  { single = 80 },
]